export const AccountActionTypes = {
  SET_LANDING_SEED: 'ACCOUNT/SET_LANDING_SEED',
  SET_LANDING_COMPLETE: 'ACCOUNT/SET_LANDING_COMPLETE',
  SET_ACCOUNT_INFO: 'ACCOUNT/SET_ACCOUNT_INFO'
};

export const MainActionTypes = {
  SET_PASSWORD: 'MAIN/SET_PASSWORD',
  SET_CURRENT_CONVERSATION_ROOT: 'MAIN/SET_CURRENT_CONVERSATION_ROOT',
  SET_SELF_MAM_ROOT: 'MAIN/SET_SELF_MAM_ROOT'
};

export const UIActionTypes = {
  OPEN_NOTIFICATION: 'UI/OPEN_NOTIFICATION',
  CLOSE_NOTIFICATION: 'UI/CLOSE_NOTIFICATION',
  START_LOADING_APP: 'UI/START_LOADING_APP',
  FINISH_LOADING_APP: 'UI/FINISH_LOADING_APP',
  START_LOADING_CONVERSATION_LIST: 'UI/START_LOADING_CONVERSATION_LIST',
  FINISH_LOADING_CONVERSATION_LIST: 'UI/FINISH_LOADING_CONVERSATION_LIST',
  START_LOADING_MESSAGE_LIST: 'UI/START_LOADING_MESSAGE_LIST',
  FINISH_LOADING_MESSAGE_LIST: 'UI/FINISH_LOADING_MESSAGE_LIST'
};

export const SettingsActionTypes = {
  SET_NODE_DOMAIN: 'SETTINGS/SET_NODE_DOMAIN',
  SET_IS_DEVNET: 'SETTINGS/SET_IS_DEVNET',
  SET_IS_LOCAL_POW: 'SETTINGS/SET_IS_LOCAL_POW'
};
